import { describe, expect, it, beforeEach } from 'vitest';
import { createClient, runMigrations, type HipppoDb } from '../../src/db/index.js';
import { projects, skills, type Skill } from '../../src/db/schema.js';
import {
  DEFAULT_HALF_LIFE_DAYS,
  MIN_RECENCY_FLOOR,
  computeSkillRank,
  listSkillsForRecall,
  promoteSkillToProject,
} from '../../src/learning/skills-rank.js';

function mkSkill(overrides: Partial<Skill> = {}): Skill {
  return {
    id: 'sk-' + Math.random().toString(36).slice(2),
    projectId: 'p1',
    agentId: 'a1',
    title: 't',
    contentMd: '# t',
    triggerPattern: null,
    timesUsed: 0,
    timesImproved: 0,
    successRate: 0,
    autoGenerated: true,
    version: 1,
    parentVersionId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    ...overrides,
  } as Skill;
}

describe('computeSkillRank', () => {
  it('base score for a fresh zero-use skill = 1.0 (baseWeight=1 × recency=1 × use=1 × version=1)', () => {
    const now = Date.parse('2026-04-16T00:00:00Z');
    const r = computeSkillRank(mkSkill({ updatedAt: new Date(now).toISOString() }), { now });
    expect(r.rank).toBeCloseTo(1.0, 5);
    expect(r.recency).toBe(1);
    expect(r.ageDays).toBe(0);
  });

  it('recency decays to 0.5 at one half-life', () => {
    const now = Date.parse('2026-04-16T00:00:00Z');
    const thirtyDaysAgo = now - 30 * 24 * 60 * 60 * 1000;
    const r = computeSkillRank(
      mkSkill({ updatedAt: new Date(thirtyDaysAgo).toISOString() }),
      { now, halfLifeDays: DEFAULT_HALF_LIFE_DAYS },
    );
    expect(r.recency).toBeCloseTo(0.5, 4);
    expect(r.ageDays).toBeCloseTo(30, 1);
  });

  it('recency floors at MIN_RECENCY_FLOOR (ancient skill still discoverable)', () => {
    const now = Date.parse('2026-04-16T00:00:00Z');
    const yearsAgo = now - 5 * 365 * 24 * 60 * 60 * 1000;
    const r = computeSkillRank(mkSkill({ updatedAt: new Date(yearsAgo).toISOString() }), { now });
    expect(r.recency).toBeGreaterThanOrEqual(MIN_RECENCY_FLOOR);
  });

  it('high successRate + heavy use lifts rank above a fresh unused skill', () => {
    const now = Date.parse('2026-04-16T00:00:00Z');
    const fresh = computeSkillRank(
      mkSkill({ updatedAt: new Date(now - 10 * 24 * 60 * 60 * 1000).toISOString() }),
      { now },
    );
    const proven = computeSkillRank(
      mkSkill({
        updatedAt: new Date(now - 10 * 24 * 60 * 60 * 1000).toISOString(),
        successRate: 0.9,
        timesUsed: 50,
        timesImproved: 3,
      }),
      { now },
    );
    expect(proven.rank).toBeGreaterThan(fresh.rank);
  });
});

describe('listSkillsForRecall', () => {
  let db: HipppoDb;
  beforeEach(async () => {
    db = createClient({ databaseUrl: ':memory:' });
    runMigrations(db);
    await db.insert(projects).values({ id: 'p1', name: 'p1' });
  });

  it('ranks skills from most to least useful (fresh + successful beats stale)', async () => {
    const now = Date.now();
    const stale = now - 90 * 24 * 60 * 60 * 1000;
    await db.insert(skills).values({
      projectId: 'p1',
      agentId: 'a1',
      title: 'stale-skill',
      contentMd: 'x',
      successRate: 0.3,
      timesUsed: 2,
      createdAt: new Date(stale).toISOString(),
      updatedAt: new Date(stale).toISOString(),
    });
    await db.insert(skills).values({
      projectId: 'p1',
      agentId: 'a1',
      title: 'hot-skill',
      contentMd: 'y',
      successRate: 0.9,
      timesUsed: 20,
    });

    const results = await listSkillsForRecall(db, 'p1', { now });
    expect(results[0]?.skill.title).toBe('hot-skill');
    expect(results[1]?.skill.title).toBe('stale-skill');
    expect(results[0]!.rank).toBeGreaterThan(results[1]!.rank);
  });

  it('drops superseded versions (parent skipped when child exists)', async () => {
    const [parent] = await db
      .insert(skills)
      .values({
        projectId: 'p1',
        agentId: 'a1',
        title: 'v1-skill',
        contentMd: 'old',
      })
      .returning();
    await db.insert(skills).values({
      projectId: 'p1',
      agentId: 'a1',
      title: 'v1-skill',
      contentMd: 'new',
      version: 2,
      parentVersionId: parent!.id,
    });
    const results = await listSkillsForRecall(db, 'p1');
    expect(results).toHaveLength(1);
    expect(results[0]?.skill.contentMd).toBe('new');
  });

  it('query filter matches title + triggerPattern (case-insensitive substring)', async () => {
    await db.insert(skills).values({
      projectId: 'p1',
      agentId: 'a1',
      title: 'Postgres Migration',
      contentMd: '.',
      triggerPattern: 'migrate database',
    });
    await db.insert(skills).values({
      projectId: 'p1',
      agentId: 'a1',
      title: 'Slack Notifier',
      contentMd: '.',
    });
    const r1 = await listSkillsForRecall(db, 'p1', { query: 'postgres' });
    expect(r1.map((s) => s.skill.title)).toEqual(['Postgres Migration']);
    const r2 = await listSkillsForRecall(db, 'p1', { query: 'migrate' });
    expect(r2.map((s) => s.skill.title)).toEqual(['Postgres Migration']);
    const r3 = await listSkillsForRecall(db, 'p1', { query: 'slack' });
    expect(r3.map((s) => s.skill.title)).toEqual(['Slack Notifier']);
  });

  it('surfaces skills from OTHER agents in the same project (cross-agent migration)', async () => {
    await db.insert(skills).values({
      projectId: 'p1',
      agentId: 'agent-A',
      title: 'from-A',
      contentMd: '.',
      successRate: 0.8,
      timesUsed: 5,
    });
    await db.insert(skills).values({
      projectId: 'p1',
      agentId: 'agent-B',
      title: 'from-B',
      contentMd: '.',
    });
    const all = await listSkillsForRecall(db, 'p1');
    expect(all.map((s) => s.skill.title).sort()).toEqual(['from-A', 'from-B']);
    const onlyA = await listSkillsForRecall(db, 'p1', { agentId: 'agent-A' });
    expect(onlyA.map((s) => s.skill.title)).toEqual(['from-A']);
  });
});

describe('promoteSkillToProject', () => {
  let db: HipppoDb;
  beforeEach(async () => {
    db = createClient({ databaseUrl: ':memory:' });
    runMigrations(db);
    await db.insert(projects).values({ id: 'p1', name: 'p1' });
  });

  it('creates a project-wide copy with agentId=*project and parentVersionId=source', async () => {
    const [source] = await db
      .insert(skills)
      .values({
        projectId: 'p1',
        agentId: 'a-source',
        title: 'proven-skill',
        contentMd: 'markdown',
        successRate: 0.9,
        timesUsed: 20,
      })
      .returning();
    const promoted = await promoteSkillToProject(db, source!.id);
    expect(promoted).not.toBeNull();
    expect(promoted!.agentId).toBe('*project');
    expect(promoted!.parentVersionId).toBe(source!.id);
    expect(promoted!.title).toBe('proven-skill');
    // Independent metrics — promoted copy starts fresh.
    expect(promoted!.timesUsed).toBe(0);
  });

  it('returns null when source skill does not exist', async () => {
    const out = await promoteSkillToProject(db, 'nope');
    expect(out).toBeNull();
  });
});
