import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { closeClient, createClient, runMigrations, type HipppoDb } from '../../src/db/index.js';
import { projects, skills, skillImprovements } from '../../src/db/schema.js';
import { DeterministicEmbeddingProvider } from '../../src/decisions/index.js';
import {
  listLatestSkills,
  maybeCreateSkill,
  maybeImproveSkill,
  recordSkillUse,
  type SkillImprover,
  type SkillWriter,
} from '../../src/learning/index.js';
import { eq } from 'drizzle-orm';

let db: HipppoDb;
let projectId: string;
const embed = new DeterministicEmbeddingProvider(256, 3);

beforeEach(async () => {
  db = createClient({ databaseUrl: ':memory:' });
  runMigrations(db);
  const [p] = await db.insert(projects).values({ name: 'T' }).returning();
  projectId = p!.id;
});
afterEach(() => closeClient(db));

describe('maybeCreateSkill', () => {
  const writer: SkillWriter = async () => ({
    title: 'Fix flaky integration test',
    contentMd: '---\ntitle: Fix flaky\n---\n\nSteps…',
    triggerPattern: 'flaky test',
  });

  it('declines below the minToolCalls threshold', async () => {
    const r = await maybeCreateSkill(
      db,
      { projectId, agentId: 'a', toolCallsCount: 2, summary: 's', fullText: 'f' },
      writer,
      { minToolCalls: 5 },
    );
    expect(r.reason).toBe('too-few-tool-calls');
    expect(r.created).toBeNull();
  });

  it('persists when writer returns a draft', async () => {
    const r = await maybeCreateSkill(
      db,
      { projectId, agentId: 'a', toolCallsCount: 6, summary: 's', fullText: 'f' },
      writer,
    );
    expect(r.reason).toBe('created');
    expect(r.created?.title).toBe('Fix flaky integration test');
    expect(r.created?.autoGenerated).toBe(true);
    expect(r.created?.version).toBe(1);
  });

  it('dedups against a near-duplicate existing skill', async () => {
    await maybeCreateSkill(
      db,
      { projectId, agentId: 'a', toolCallsCount: 6, summary: 's', fullText: 'f' },
      writer,
      { embeddingProvider: embed, dedupSim: 0.9 },
    );
    const again = await maybeCreateSkill(
      db,
      { projectId, agentId: 'a', toolCallsCount: 6, summary: 's', fullText: 'f' },
      writer,
      { embeddingProvider: embed, dedupSim: 0.9 },
    );
    expect(again.reason).toBe('deduped');
    expect(again.duplicateOf).toBeDefined();
  });

  it('writer returning null → declined', async () => {
    const r = await maybeCreateSkill(
      db,
      { projectId, agentId: 'a', toolCallsCount: 6, summary: 's', fullText: 'f' },
      async () => null,
    );
    expect(r.reason).toBe('writer-declined');
  });
});

describe('maybeImproveSkill', () => {
  async function seedSkill(): Promise<string> {
    const [row] = await db
      .insert(skills)
      .values({
        projectId,
        agentId: 'a',
        title: 'T',
        contentMd: 'v1 content',
        version: 1,
      })
      .returning();
    return row!.id;
  }

  const improver: SkillImprover = async () => ({
    newContentMd: 'v2 content',
    diff: '+v2\n-v1',
    reason: 'failure root cause',
    triggeredBy: 'failure',
  });

  it('creates a new skill row with bumped version + parent pointer + audit row', async () => {
    const id = await seedSkill();
    const r = await maybeImproveSkill(db, id, { errorMessage: 'boom', evidence: '…' }, improver, {
      improvedBy: 'agent:lead',
    });
    expect(r.improved?.version).toBe(2);
    expect(r.improved?.parentVersionId).toBe(id);
    expect(r.improved?.timesImproved).toBe(1);
    expect(r.improvement?.previousVersion).toBe(1);
    expect(r.improvement?.newVersion).toBe(2);

    const audits = await db
      .select()
      .from(skillImprovements)
      .where(eq(skillImprovements.skillId, r.improved!.id));
    expect(audits).toHaveLength(1);
    expect(audits[0]!.triggeredBy).toBe('failure');
    expect(audits[0]!.improvedBy).toBe('agent:lead');
  });

  it('improver returning null → no changes', async () => {
    const id = await seedSkill();
    const r = await maybeImproveSkill(
      db,
      id,
      { errorMessage: 'x', evidence: 'y' },
      async () => null,
    );
    expect(r.improved).toBeNull();
  });

  it('throws on missing skill id', async () => {
    await expect(
      maybeImproveSkill(
        db,
        '00000000-0000-4000-8000-000000000000',
        { errorMessage: 'x', evidence: 'y' },
        improver,
      ),
    ).rejects.toThrow(/not found/);
  });
});

describe('listLatestSkills', () => {
  it('returns the highest version per title', async () => {
    await db.insert(skills).values([
      { projectId, agentId: 'a', title: 'T', contentMd: 'v1', version: 1 },
      { projectId, agentId: 'a', title: 'T', contentMd: 'v2', version: 2 },
      { projectId, agentId: 'a', title: 'T', contentMd: 'v3', version: 3 },
      { projectId, agentId: 'a', title: 'U', contentMd: 'u1', version: 1 },
    ]);
    const latest = await listLatestSkills(db, projectId, 'a');
    expect(latest).toHaveLength(2);
    const titles = latest.reduce<Record<string, number>>(
      (acc, s) => ({ ...acc, [s.title]: s.version }),
      {},
    );
    expect(titles).toEqual({ T: 3, U: 1 });
  });
});

describe('recordSkillUse', () => {
  it('updates timesUsed and success rate', async () => {
    const [row] = await db
      .insert(skills)
      .values({ projectId, agentId: 'a', title: 'T', contentMd: 'c', version: 1 })
      .returning();
    await recordSkillUse(db, row!.id, true);
    await recordSkillUse(db, row!.id, true);
    await recordSkillUse(db, row!.id, false);
    const [fresh] = await db.select().from(skills).where(eq(skills.id, row!.id));
    expect(fresh!.timesUsed).toBe(3);
    expect(fresh!.successRate).toBeCloseTo(2 / 3, 4);
  });

  it('no-op for unknown id', async () => {
    await expect(
      recordSkillUse(db, '00000000-0000-4000-8000-000000000000', true),
    ).resolves.toBeUndefined();
  });
});
