/**
 * Skill auto-creation + self-improvement.
 *
 * Skills are chunks of agentskills.io-format markdown that generalize
 * sessions agents have handled before. The LLM writes them; this module
 * is the persistence + trigger + dedup layer.
 *
 *   maybeCreateSkill(db, session, writer, opts)
 *     - Fires when the session did >= opts.minToolCalls tool calls
 *       (default 5). Writer converts the session into a SkillDraft;
 *       dedup checks the existing skills for the same agent and skips
 *       if there's a near-duplicate (embedding cosine >= 0.92 by default).
 *
 *   maybeImproveSkill(db, skillId, failure, improver, opts)
 *     - Takes a failure record + the current skill, hands both to
 *       `improver`. If it returns a diff + new content, we bump the
 *       version (skills.version), copy the previous row's id into
 *       parentVersionId, and log a skill_improvements row.
 *
 * No LLM is called here directly. Writer / improver interfaces are
 * injected and usually wrap an LLM call.
 */

import { and, desc, eq } from 'drizzle-orm';
import type { HipppoDb } from '../db/client.js';
import {
  skillImprovements,
  skills,
  type NewSkill,
  type NewSkillImprovement,
  type Skill,
} from '../db/schema.js';
import {
  cosineSimilarity,
  deserializeEmbedding,
  serializeEmbedding,
  type EmbeddingProvider,
} from '../decisions/embeddings.js';

export const DEFAULT_MIN_TOOL_CALLS_FOR_SKILL = 5;
export const DEFAULT_DEDUP_SIM = 0.92;

export interface SessionSnapshot {
  projectId: string;
  agentId: string;
  toolCallsCount: number;
  /** Short summary of what happened. Usually from SessionSummary.finalText or a dedicated summarizer. */
  summary: string;
  /** Full text for embedding / skill writer context. */
  fullText: string;
}

export interface SkillDraft {
  title: string;
  /** agentskills.io Markdown. Must include a frontmatter block per spec. */
  contentMd: string;
  /** Optional literal / regex that, when matched against a user message, suggests this skill. */
  triggerPattern?: string;
}

export type SkillWriter = (session: SessionSnapshot) => Promise<SkillDraft | null>;

export interface MaybeCreateSkillOptions {
  /** Minimum tool calls in the session to even consider skill creation. */
  minToolCalls?: number;
  /** Dedup threshold against existing skills for the same agent. */
  dedupSim?: number;
  /** Embedding provider for dedup. If omitted, dedup is skipped (tests / offline). */
  embeddingProvider?: EmbeddingProvider;
}

export interface SkillCreationResult {
  created: Skill | null;
  reason: 'too-few-tool-calls' | 'writer-declined' | 'deduped' | 'created';
  duplicateOf?: string;
}

export async function maybeCreateSkill(
  db: HipppoDb,
  session: SessionSnapshot,
  writer: SkillWriter,
  opts: MaybeCreateSkillOptions = {},
): Promise<SkillCreationResult> {
  const minCalls = opts.minToolCalls ?? DEFAULT_MIN_TOOL_CALLS_FOR_SKILL;
  if (session.toolCallsCount < minCalls) {
    return { created: null, reason: 'too-few-tool-calls' };
  }

  const draft = await writer(session);
  if (!draft) return { created: null, reason: 'writer-declined' };

  if (opts.embeddingProvider) {
    const newVec = await opts.embeddingProvider.embed(`${draft.title}\n${draft.contentMd}`);
    const existing = await db
      .select()
      .from(skills)
      .where(and(eq(skills.projectId, session.projectId), eq(skills.agentId, session.agentId)));
    const threshold = opts.dedupSim ?? DEFAULT_DEDUP_SIM;
    for (const e of existing) {
      if (!e.contentMd) continue;
      // We don't currently store skill embeddings. Compute on the fly.
      // (Storing them is a Phase 2.x iteration; volumes are small for now.)
      const eVec = await opts.embeddingProvider.embed(`${e.title}\n${e.contentMd}`);
      if (cosineSimilarity(newVec, eVec) >= threshold) {
        return { created: null, reason: 'deduped', duplicateOf: e.id };
      }
    }
  }

  const payload: NewSkill = {
    projectId: session.projectId,
    agentId: session.agentId,
    title: draft.title,
    contentMd: draft.contentMd,
    ...(draft.triggerPattern && { triggerPattern: draft.triggerPattern }),
    autoGenerated: true,
    version: 1,
  };

  const [row] = await db.insert(skills).values(payload).returning();
  if (!row) throw new Error('maybeCreateSkill: insert returned no row');
  return { created: row, reason: 'created' };
}

// ─────────────────────────────────────────────────────────────────────────────
// Skill self-improvement
// ─────────────────────────────────────────────────────────────────────────────

export interface SkillFailure {
  sessionId?: string;
  errorMessage: string;
  /** Evidence — transcript slice, tool output, user complaint. */
  evidence: string;
}

export interface SkillImprovement {
  newContentMd: string;
  diff: string;
  reason: string;
  triggeredBy: 'failure' | 'deviation' | 'manual' | 'outcome';
}

export type SkillImprover = (
  skill: Skill,
  failure: SkillFailure,
) => Promise<SkillImprovement | null>;

export interface MaybeImproveSkillOptions {
  improvedBy?: string; // who did it (agent id, user id)
}

export interface SkillImprovementResult {
  improved: Skill | null;
  improvement?: { id: string; previousVersion: number; newVersion: number };
}

/**
 * Ask the improver for a diff. If returned, creates a new skill row (bumped
 * version, parentVersionId pointer) and a skill_improvements audit row.
 */
export async function maybeImproveSkill(
  db: HipppoDb,
  skillId: string,
  failure: SkillFailure,
  improver: SkillImprover,
  opts: MaybeImproveSkillOptions = {},
): Promise<SkillImprovementResult> {
  const [current] = await db.select().from(skills).where(eq(skills.id, skillId)).limit(1);
  if (!current) throw new Error(`maybeImproveSkill: skill not found: ${skillId}`);

  const imp = await improver(current, failure);
  if (!imp) return { improved: null };

  const newVersion = current.version + 1;
  const payload: NewSkill = {
    projectId: current.projectId,
    agentId: current.agentId,
    title: current.title,
    contentMd: imp.newContentMd,
    ...(current.triggerPattern && { triggerPattern: current.triggerPattern }),
    autoGenerated: current.autoGenerated,
    version: newVersion,
    parentVersionId: current.id,
    timesUsed: 0,
    timesImproved: current.timesImproved + 1,
  };
  const [newRow] = await db.insert(skills).values(payload).returning();
  if (!newRow) throw new Error('maybeImproveSkill: insert returned no row');

  const improvementPayload: NewSkillImprovement = {
    skillId: newRow.id,
    previousVersion: current.version,
    newVersion,
    diff: imp.diff,
    reason: imp.reason,
    triggeredBy: imp.triggeredBy,
    improvedBy: opts.improvedBy ?? 'system',
  };
  const [improvementRow] = await db
    .insert(skillImprovements)
    .values(improvementPayload)
    .returning();
  if (!improvementRow) throw new Error('maybeImproveSkill: improvement insert failed');

  return {
    improved: newRow,
    improvement: {
      id: improvementRow.id,
      previousVersion: current.version,
      newVersion,
    },
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Convenience queries
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Latest version of each skill (by title, per agent). Skip rows that have
 * been superseded by a newer `version`.
 */
export async function listLatestSkills(
  db: HipppoDb,
  projectId: string,
  agentId: string,
): Promise<Skill[]> {
  const rows = await db
    .select()
    .from(skills)
    .where(and(eq(skills.projectId, projectId), eq(skills.agentId, agentId)))
    .orderBy(desc(skills.version));

  const latestByTitle = new Map<string, Skill>();
  for (const r of rows) {
    if (!latestByTitle.has(r.title)) latestByTitle.set(r.title, r);
  }
  return [...latestByTitle.values()];
}

/** Increment `timesUsed` and update success rate. Call when a skill is applied. */
export async function recordSkillUse(
  db: HipppoDb,
  skillId: string,
  succeeded: boolean,
): Promise<void> {
  const [row] = await db.select().from(skills).where(eq(skills.id, skillId)).limit(1);
  if (!row) return;
  const newTimesUsed = row.timesUsed + 1;
  const successes = row.successRate * row.timesUsed + (succeeded ? 1 : 0);
  const newSuccessRate = successes / newTimesUsed;
  await db
    .update(skills)
    .set({ timesUsed: newTimesUsed, successRate: newSuccessRate })
    .where(eq(skills.id, skillId));
}

/** For tests / callbacks that want the vector as a string. */
export function encodeVector(v: Float32Array): string {
  return serializeEmbedding(v);
}

export function decodeVector(raw: string): Float32Array {
  return deserializeEmbedding(raw);
}
